/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psyriccio.laftst;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author psyriccio
 */
public class ChangeLafForm extends javax.swing.JInternalFrame {

    final private JFrame mainFrame;
    
    /**
     * Creates new form ChangeLafForm
     */
    public ChangeLafForm(ListModel<LafListModel.Item> model, JFrame mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
        lafList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lafList = new javax.swing.JList<>();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lafList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lafListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lafList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lafListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lafListValueChanged
        try {
            UIManager.setLookAndFeel(lafList.getSelectedValue().getFullName());
            SwingUtilities.updateComponentTreeUI(mainFrame);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ChangeLafForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lafListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<LafListModel.Item> lafList;
    // End of variables declaration//GEN-END:variables
}
